# Generated by Django 2.2.1 on 2020-01-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=2500)),
                ('branch_choice', models.IntegerField(choices=[('1', 'Computer Science Engineering'), ('2', 'Civil Engineering\t'), ('3', 'Automobile Engineering'), ('4', 'Electronics and Communication Engineering'), ('5', 'Electrical Engineering'), ('6', 'Electronics and Instrumentation'), ('7', 'Electrical and Electronics Engineering'), ('8', 'Fire and Safety'), ('9', 'Information Technology'), ('10', 'Mechanical Engineering')], max_length=50)),
                ('file_semester', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default='1', max_length=50)),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
