# Generated by Django 2.2.1 on 2020-01-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes_model',
            name='branch_choice',
            field=models.IntegerField(choices=[('cse', 'Computer Science Engineering'), ('ce', 'Civil Engineering\t'), ('au', 'Automobile Engineering'), ('ec', 'Electronics and Communication Engineering'), ('ee', 'Electrical Engineering'), ('ex', 'Electronics and Instrumentation'), ('eee', 'Electrical and Electronics Engineering'), ('ft', 'Fire and Safety'), ('it', 'Information Technology'), ('me', 'Mechanical Engineering')], default='cse'),
        ),
    ]
