# Generated by Django 2.2.1 on 2020-01-15 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_model_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes_model',
            name='author',
        ),
    ]
