# Generated by Django 2.2.1 on 2020-01-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200115_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes_model',
            name='branch_choice',
            field=models.CharField(choices=[('Computer Science Engineering', 'Computer Science Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Automobile Engineering', 'Automobile Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Electronics Engineering', 'Electronics and Instrumentation'), ('Electrical Engineering', 'Electrical and Electronics Engineering'), ('Fire Engineering', 'Fire and Safety'), ('Information Engineering', 'Information Technology'), ('Mechanical Engineering', 'Mechanical Engineering')], default='cse', max_length=50),
        ),
    ]
