# Generated by Django 2.2.10 on 2020-02-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20200118_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes_model',
            name='syllabus',
            field=models.TextField(default='No Syllabus Availibe Yet', max_length=200),
        ),
    ]
