# Generated by Django 2.2.1 on 2020-01-16 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20200116_0559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes_model',
            old_name='subject',
            new_name='title',
        ),
    ]
