# Generated by Django 2.2.10 on 2020-02-22 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20200222_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website_Gen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.TextField(max_length=200)),
                ('date_established', models.DateTimeField()),
                ('files', models.FileField(upload_to='')),
                ('syllabus', models.TextField(default='No Syllabus Availible Yet', max_length=200)),
                ('branch_availible', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='notes.Notes_Model'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
